# -*- coding: utf-8 -*-
"""Drug_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iC8vN0DfgIfURj0tvVDqgYb_iz0_et0l
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

data=pd.read_csv('/content/drug200.csv')

data.head()

X=data.drop(columns='Drug',axis=1)
Y=data.drop(columns=['Age','Sex','BP','Cholesterol','Na_to_K'],axis=1)

X=X.replace("M",1)
X=X.replace("F",0)
X=X.replace("HIGH",1)
X=X.replace("LOW",0)

X.head()

X=X.replace('NORMAL',2)

model=keras.Sequential(
    [
        keras.layers.Flatten(input_shape=(5,)),
        keras.layers.Dense(20,activation='relu'),
        keras.layers.Dense(5,activation='sigmoid')
    ]
)

model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

Y.shape

print(Y)

Y=Y.replace("DrugY",0)
Y=Y.replace("drugX",1)
Y=Y.replace("drugC",2)
Y=Y.replace("drugA",3)
Y=Y.replace("drugB",4)

Y.head()

model.fit(X,Y,validation_split=0.1,epochs=10)

